#!/bin/sh
eval $(gpg-agent --daemon) &
dunst &
slack &
xrdb -merge ~/.Xresources
xrandr --output LVDS1 --auto
~/.fehbg
~/.local/scripts/status &
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'lock' '' &
